[[SoapyLMS7]]
arch = "aarch64"
git-tree-sha1 = "fc437f93a51028855802c71871b208764b284ac4"
os = "macos"

    [[SoapyLMS7.download]]
    sha256 = "a6c61d661c379de78a68301ecbe6ff8a79d786544ffd7e6d07191f7ebec8cad4"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.aarch64-apple-darwin.tar.gz"
[[SoapyLMS7]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96222cb7cd6ba7771e4d8c432e0ace3a270cc0fb"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "7a5b1421f8aee5b1be4741a63c8cbf3155db6d25716eb7926401ea4ef90be22d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27a68bc2731997bbb0ae2ef024f539248112e4b5"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "7ff06dae77623f246f7ccf6c9997dcbb1a11c7cb2ec954a7574f80a38a64dadd"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a644b6444d35bd5cb2c7de2ad265b9b08e94828"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "094d81cefe1a85f80e88a23a42e86a4a00d205a626348dba9fd353f9c58982eb"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.aarch64-linux-musl-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2de674b85094763cacc49d69d2e5c02e345ca2e"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "5a32864b47b2736211121158d65296d35c1114d50da196b8b60f5f13d28fc71a"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.aarch64-linux-musl-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14d83856f85e5f049a44567fd6d0545b532de1f1"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "38e8f7696439b84bfae8ce63525dd627e23798c0b28127549bf16a0c1b8493a7"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "341ae8fcf26e01d5af5b216ea0e2637d08513bb3"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "fb24216325acc7cbf9773679a97a9be8589d02eb76d1ef24772d18dce6d0d3e0"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f40cf38646cadec6dab59de0ec8dc518e10fc657"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "88dc208fc7f630609ecf28366eec757d638e8fcc3aa29272232e7200d6295bee"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e6ac76ccee83db13fc58f17b51447828876b482"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "d34f5d5328eede1fb5474d1e4be4f757f72f75640ec6a4c267692da56a714027"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e239e9b96302cb1b1ed0322c0642cc5dbf879539"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "8cc67386452e0733f6a35dad810c4757bb1d7dfc8a64fcabd758c403cba8b5ba"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1593a11e036dc8f12b3bf4c65c69d70ef231d32"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "77ca25cdd5bc01b6cad45d0a295a8e97e4bb3963a6ceb08dc25d536004477c79"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ff6140789e10bddecd2ad236c547226411cab90"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "e08541e08ed7ffbbb13f01a63c30c03048fc16401497eefeb55e488f4d448ba9"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11253b86647ea863f18440a2f8056272221c3c4b"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "f33c23b55143721a8a3b52717c02dc50b2b15afa28894a10b7c85cb89640464e"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca09ca729a737d5d68549fe9bd4b2fdf6f9e9403"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "83f3cb280f4eb7502b7b6bb2339b27053c116e722e47ed52a3933cb8211e002d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.i686-linux-gnu-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d424fc698f67a9d1031580ef14e8898f52b07511"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "a87fe2d002da52a68718de244ddb9c43efb597879855458e2a3710e2c9c00c69"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.i686-linux-gnu-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "959a7ff3dad097a7846b64f572f7929fdb226c1f"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "549c05c7c02c5bfebf3f5c030ad1366826901dec2f3d3325db4092afd44e13da"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.i686-linux-musl-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "403acbf1672c452f9c0b2e3124404d58496a341d"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "8b8601faa48520c821a3bd92cd7c7375a33a2fbd88de9c01edcf7c994bfb8d4c"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.i686-linux-musl-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a128e5e9f7c71df4735ac2bdeea2874a7efbd340"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "6afa41fa25588f150bf69bb76efdf0f252a44523b923b665fed4d449baf9e73d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a95d27b7365edf794f6b5ab8401cc3e4cef67ae"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "fd927a9c717ee1857c061fb14d45074249365b23276e2e24f18ee38b5f4d6241"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "x86_64"
git-tree-sha1 = "1dbf3eeba8e8cb0e719674beccd993b2b37da374"
os = "macos"

    [[SoapyLMS7.download]]
    sha256 = "e0fd817783584697e9537d611a1fe3bf405b0128893c8a015a73c7f056a5aac2"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.x86_64-apple-darwin.tar.gz"
[[SoapyLMS7]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77fc4d1fe7162edb539879fe61b156c84e952475"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "4848ffd4e4cc7e610e36b691872126a9093503dc7a8b932f394e992a390861ba"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21d7bc4db58fed1021d1aab816c55677f8725f44"
libc = "glibc"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "cc1415bf17c2d9908c8350d5784c2f751d777ff0e00a8193ee085cc5c2f946a5"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30efb8b664c3d678e03a6c5297091276b0bdec0f"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "573c7e0aac0f1529edf28e62a5b9ffb1d1709a059eb2bce518974aa45a3ebfa5"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.x86_64-linux-musl-cxx03.tar.gz"
[[SoapyLMS7]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06ab47a828240948d7889ec6dfadfb1c6a889434"
libc = "musl"
os = "linux"

    [[SoapyLMS7.download]]
    sha256 = "2a7daee76f94ae95d56c204cb92446ec335956d8b6bf5c1de6098af4005101a3"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.x86_64-linux-musl-cxx11.tar.gz"
[[SoapyLMS7]]
arch = "x86_64"
git-tree-sha1 = "794ca96338e9771a84968ee64d2a2304547b2cdf"
os = "freebsd"

    [[SoapyLMS7.download]]
    sha256 = "da312a75a48b61c552c503fbd8e7d56f9f602874c456a64a56738ea1da9502b3"
    url = "https://github.com/JuliaBinaryWrappers/SoapyLMS7_jll.jl/releases/download/SoapyLMS7-v20.10.0+0/SoapyLMS7.v20.10.0.x86_64-unknown-freebsd.tar.gz"
